updared config [ci skip] [ci skip]

diff --git a/.Rproj.user/A6C8DCBE/sources/s-23123D7B/1FB73C5C-contents b/.Rproj.user/A6C8DCBE/sources/s-23123D7B/1FB73C5C-contents
--- a/.Rproj.user/A6C8DCBE/sources/s-23123D7B/1FB73C5C-contents
+++ b/.Rproj.user/A6C8DCBE/sources/s-23123D7B/1FB73C5C-contents
@@ -16,8 +16,8 @@ if ! git diff-index --quiet HEAD --; then
     git add -fA
     git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
     git push -f -q origin $SRC_BRANCH
-    echo "Aborting."
-    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+    #echo "Aborting."
+    #[[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
 
 #DEPLOY_BRANCH="master"
